            - name: Pages Preview
  # You may pin to the exact commit or the version.
  # uses: EndBug/pages-preview@3e2aef8b39eb77522c278172e94c8628b2b58bcc
  uses: EndBug/pages-preview@v1.1.2
  with:
    # The directory in which the website has been built, in the a/b/c format
    build_dir: 
    # The GitHub Pages base URL of the preview repo (e.g. https://octocat.github.io/preview)
    preview_base_url: 
    # The repository to push previews to, in the Owner/Name format
    preview_repo: 
    # The token to access the preview repo
    preview_token: 
    # The name of the environment to use for the deployment
    deployment_env: # optional, default is preview
    # Whether to use the deployments API
    deployments: # optional, default is true
    # The name of the author of the resulting commit
    git_author_name: # optional, default is ${{ github.actor }}
    # The email of the author of the resulting commit
    git_author_email: # optional, default is ${{ github.actor }}@users.noreply.github.com
    # The committer of the resulting commit
    git_committer_name: # optional
    # The email of the committer of the resulting commit
    git_committer_email: # optional
    # Whether to comment on PRs
    pr_comment: # optional, default is true
    # The name of the branch that hosts the previews
    preview_branch: # optional, default is gh-pages
    # The name of the workflow file that contains the comment workflow in the preview repo. If you use my template, the name is already 'preview.yml'
    preview_workflow_file_name: # optional, default is preview.yml
          
